# Generated by Django 4.0.5 on 2022-06-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=130, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('patronymic', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d')),
                ('years', models.IntegerField()),
                ('online_consultaion', models.BooleanField(default=True)),
                ('experience', models.SmallIntegerField(default='1')),
                ('conditions_to_appmt', models.TextField(default='Бесплатно', max_length=1000)),
                ('accepts_declarations', models.BooleanField(default=True)),
                ('cabinet', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PolyclinycSpecialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PolyclynicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_weekday', models.IntegerField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], unique=True)),
                ('to_weekday', models.IntegerField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], unique=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Polyclinyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField()),
                ('doctor_poly', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor workplace+', to='hospital.doctor')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.polyclynicschedule')),
                ('specialities', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.polyclinycspecialities')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openning_times', models.ManyToManyField(to='hospital.workingtimes')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.gender'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='polyclinyc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Клиника доктора+', to='hospital.polyclinyc'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctorschedule'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specitality',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='hospital.doctorspeciality'),
        ),
    ]
