# Generated by Django 4.0.5 on 2022-06-24 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
            ],
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'verbose_name': 'Общий график доктора', 'verbose_name_plural': 'Общие графики докторов'},
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='online_consultaion',
            new_name='online_consultation',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='polyclinyc',
        ),
        migrations.RemoveField(
            model_name='polyclinyc',
            name='doctor_poly',
        ),
        migrations.AddField(
            model_name='doctor',
            name='polyclynic',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors work place+', to='hospital.polyclinyc'),
        ),
        migrations.AddField(
            model_name='polyclinyc',
            name='doctor',
            field=models.ManyToManyField(to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='polyclynicschedule',
            name='workingtimes',
            field=models.ManyToManyField(to='hospital.workingtimes'),
        ),
        migrations.RemoveField(
            model_name='polyclinyc',
            name='specialities',
        ),
        migrations.AddField(
            model_name='polyclinyc',
            name='specialities',
            field=models.ManyToManyField(to='hospital.doctorspeciality'),
        ),
        migrations.AlterField(
            model_name='workingtimes',
            name='from_weekday',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')]),
        ),
        migrations.AlterField(
            model_name='workingtimes',
            name='to_weekday',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')]),
        ),
        migrations.DeleteModel(
            name='PolyclinycSpecialities',
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hospital.consultationschedule'),
        ),
    ]
