# Generated by Django 4.0.5 on 2022-06-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_consultationschedule_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_schedule',
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_schedule',
            field=models.ManyToManyField(related_name='consultai schedule+', to='hospital.consultationschedule'),
        ),
        migrations.AlterField(
            model_name='polyclinyc',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='hospital.doctor'),
        ),
    ]
