# Generated by Django 4.0.5 on 2022-06-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_workingtimes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='working_times',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.workingtimes'),
        ),
        migrations.AlterField(
            model_name='workingtimes',
            name='from_weekday',
            field=models.CharField(choices=[('ПОНЕДЕЛЬНИК', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=200, verbose_name='с какого дня'),
        ),
        migrations.AlterField(
            model_name='workingtimes',
            name='to_weekday',
            field=models.CharField(choices=[('ПОНЕДЕЛЬНИК', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=100),
        ),
    ]
