# Generated by Django 4.0.5 on 2022-06-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_doctor_working_times_alter_workingtimes_from_weekday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'default_related_name': 'all_doctors', 'ordering': ['-years']},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_times',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.workingtimes', verbose_name='График'),
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
