# Generated by Django 4.0.5 on 2022-06-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_doctor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrating',
            name='star',
            field=models.FloatField(),
        ),
    ]
