# Generated by Django 4.0.5 on 2022-06-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_doctorrating_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelsiReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
    ]
