# Generated by Django 4.0.5 on 2022-06-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_doctor_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='patronimyc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
