# Generated by Django 4.0.5 on 2022-06-29 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_alter_consultationschedule_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationschedule',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultai_schedule+', to='hospital.consultationschedule'),
        ),
    ]
