# Generated by Django 4.0.5 on 2022-06-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_alter_consultationschedule_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_schedule',
            field=models.ManyToManyField(blank=True, related_name='consultai_schedule+', to='hospital.consultationschedule'),
        ),
    ]
