# Generated by Django 4.0.5 on 2022-06-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_alter_doctor_consultation_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationschedule',
            name='doctor',
        ),
        migrations.AddField(
            model_name='consultationschedule',
            name='doctor',
            field=models.ManyToManyField(null=True, related_name='doctor schedule con+', to='hospital.doctor'),
        ),
    ]
