# Generated by Django 4.0.5 on 2022-06-29 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_remove_consultationschedule_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationschedule',
            name='doctor',
        ),
        migrations.AddField(
            model_name='consultationschedule',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor schedule con+', to='hospital.doctor'),
        ),
    ]
