# Generated by Django 4.0.5 on 2022-06-30 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationschedule',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='years',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Priyom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=False)),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.consultationschedule')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.doctor')),
                ('pacient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.profile')),
            ],
        ),
    ]
