# Generated by Django 4.0.5 on 2022-06-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_consultationschedule_active_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationschedule',
            old_name='active',
            new_name='zanyato',
        ),
    ]
