# Generated by Django 4.0.5 on 2022-06-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_rename_active_consultationschedule_zanyato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationschedule',
            old_name='zanyato',
            new_name='active',
        ),
    ]
