# Generated by Django 4.0.5 on 2022-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_rename_zanyato_consultationschedule_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='priyom',
            name='choicewhogo',
            field=models.CharField(choices=[('1', 'записати себе'), ('2', 'записати дитину')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='priyom',
            name='consType',
            field=models.CharField(choices=[('1', 'видеоконсльтация'), ('2', 'прийду до ликаря')], max_length=100, null=True),
        ),
    ]
